Repository frank-martinez-iest/exercise-3, pull requests merged in 2021-01, with the labels that each got.

#2 SFO-67: Create navbar
  josue/css/style.css
  josue/images/bg.jpg
  josue/index.html
  josue/js/Formvalidator.js
  josue/js/app.js
Labels: help wanted

#8 SFO-72 Unit Test Log In Feature
  josue/.gitignore
  josue/app.test.js
  josue/babel.config.js
  josue/index.html
  josue/jest.config.js
  josue/js/app-test.js
  josue/package.json
Labels: good first issue

#11 Bug/Buttons_login_and_signup_at_navbar
  francisco/js/app.js
Labels: bug
